#include "../../logging.hpp"
#include <QMainWindow>
#include <QApplication>
#include <QDate>
#include <QProcess>
#include <QGraphicsView>
#include <QGraphicsScene>
#include <QGraphicsTextItem>
#include <QMouseEvent>
#include <QKeyEvent>
#include <QGraphicsPixmapItem>
